config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "groups#index"
  resources :groups,only: [:index, :new, :create, :destroy] do
    resources :games
    namespace :api do
      resources :games, only: :index, defaults: { format: 'json' }
    end
  end
  resources :kous, only: [:create]
end

app/models/group.rb
class Group < ApplicationRecord
  with_options presence: true do
    validates :name
    validates :kou_user
    validates :otu_user
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
  end

  def new
    @group = Group.new()
    if user_signed_in?
    else
      redirect_to new_user_registration_path
    end
  end

  def create
    params[:kou_user] = current_user.id
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path
    else
      redirect_to groups_path
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @game = Game.find_by(group_id: params[:id])
    @kou = Kou.find_by(game_id: @game.id)
    @otu = Otu.find_by(game_id: @game.id)
    @group.destroy
    @kou.destroy
    @otu.destroy
    @game.destroy
    redirect_to root_path
  end

  private

  def group_params
    params.permit(:name, :otu_user, :kou_user)
  end

  def create_player
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/index.html.haml
.header
  .header__group
    = link_to new_group_path,class: "header__group--new" do
      部屋作成
  .header__title
    Title募集
  .header__devise
    - if user_signed_in?
      = link_to destroy_user_session_path, method: :delete,class: "header__devise--login" do
        = current_user.nickname
    - else
      = link_to user_session_path,class: "header__devise--login" do
        ログイン
      = link_to new_user_registration_path,class: "header__devise--new" do
        新規登録
.main
  .main__side--left
  .main__groups
    - Group.all.each do |group|
      = link_to group_games_path(group.id),class: "main__groups--group" do
        .group-name
          = group.name
        .player-name
          .player-name__kou
            = User.find(group.kou_user).nickname
          .player_name__vs
            対
          .player-name__otu
            = User.find(group.otu_user).nickname
  .main__side--right

app/views/groups/new.html.haml
.main-create
  .create-group
    = form_with url: groups_path, local: true do |f|
      .create-group__name
        = f.text_field :name, class: "SettingGroupForm__input", placeholder: "グループ名"
      .create-group__player--otu
        対戦相手を選択して下さい。<br>
        = f.collection_radio_buttons :otu_user, User.all, :id, :nickname
      .create-group__btn
        = f.submit "部屋作成", class: "SettingGroupForm__button"