config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "groups#index"
  resources :groups,only: [:index, :new, :create, :destroy] do
    resources :games
    namespace :api do
      resources :games, only: :index, defaults: { format: 'json' }
    end
  end
  resources :kous, only: [:create]
end

app/models/game.rb
class Game < ApplicationRecord
  serialize :deck,Array
  belongs_to :group
end

app/controllers/api/games_controller.rb
class Api::GamesController < ApplicationController
  def index
    @game = Game.find_by(group_id: params[:group_id])
    if params[:count].to_i < @game.turn_count
      render json:{reload: "true"}
    else
      render json:{reload: "false"}
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :get_game,only: [:index,:destroy,:update]
  before_action :get_kou_otu,only: [:destroy,:update]

  def index
    if @game
      @kou = Kou.find_by(game_id: @game.id)
      @otu = Otu.find_by(game_id: @game.id)
      get_gon
    end
  end

  def new
  end

  def create
    create_deck
    params[:condition] = "started"
    params[:field_card] = 0
    params[:turn] = "kou"
    params[:turn_count] = 0
    params[:action] = "kou"
    @kou_hand = []
    @otu_hand = []
    join_hand(@kou_hand)
    join_hand(@kou_hand)
    join_hand(@otu_hand)
    @games = Game.new(games_params)
    @games.message = "ゲームが開始されました。"
    @games.deck << params[:deck][0] << params[:deck][1]
    if @games.save
      @kou = Kou.new()
      @otu = Otu.new()
      kou_create
      otu_create
      redirect_to group_games_path(params[:group_id])
    end
  end

  def destroy
    @kou.destroy
    @otu.destroy
    @game.destroy
    redirect_to group_games_path(params[:group_id])
  end

  def update
    if @game.deck[0].length == 0
      @game.field_card = params[:number]
      @game.action = "fight"
      check_turn_player(@game.turn).hand.delete_at(params[:hand].to_i)
      if @kou.hand[0] < @otu.hand[0]
        @game.condition = "otu"
      elsif @kou.hand[0] > @otu.hand[0]
        @game.condition = "kou"
      else
        @game.condition = "draw"
      end
      update_all
      render json:{number: 0}
    else
      if params[:number].to_i == 0
        render json:{number: 0}
        turn_change_action
      else
        check_card_number(params[:number].to_i)
      end
    end
  end


  private
  def create_deck
    params[:deck] = [1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,10].shuffle
    last_card = params[:deck].pop
    params[:deck] = [params[:deck],[last_card]]
  end

  def games_params
    params.permit(:condition,:deck,:field_card,:turn,:turn_count,:action,:group_id)
  end

  def kou_create
    @kou.hand = @kou_hand
    @kou.user_id = Group.find_by(id: params[:group_id]).kou_user
    @kou.game_id = Game.find_by(group_id: params[:group_id]).id
    @kou.save
  end

  def otu_create
    @otu.hand = @otu_hand
    @otu.user_id = Group.find_by(id: params[:group_id]).otu_user
    @otu.game_id = Game.find_by(group_id: params[:group_id]).id
    @otu.save
  end

  def turn_change_action
    @game.turn = change_kou_otu(@game.turn)
    @game.action = change_kou_otu(@game.action)
    @game.turn_count += 1
    if check_turn_player(@game.turn).condition == "guard"
      check_turn_player(@game.turn).condition = ""
      draw_hand(@game.turn)
      update_all
    elsif check_turn_player(@game.turn).condition == "wise"
      change_message("未来視を発動中です...")
      if @game.deck[0].length > 2
        array = [@game.deck[0][0],@game.deck[0][1],@game.deck[0][2]]
        check_turn_player(@game.turn).hand[1] = array
        @game.deck[0] = @game.deck[0].drop(3)
        update_all
      elsif @game.deck[0].length == 2
        array = [@game.deck[0][0],@game.deck[0][1]]
        check_turn_player(@game.turn).hand[1] = array
        @game.deck[0] = @game.deck[0].drop(2)
        update_all
      else
        check_turn_player(@game.turn).condition = ""
        change_message("未来視によってカードが選ばれました。")
        draw_hand(@game.turn)
        update_all
      end
    else
    draw_hand(@game.turn)
    update_all
    end
  end

  def put_card_action
    @game.field_card = params[:number]
    check_turn_player(@game.turn).discard << params[:number]
    check_turn_player(@game.turn).hand.delete_at(params[:hand].to_i)
  end


  def update_all
    @game.save
    @kou.save
    @otu.save
  end


  def join_hand(hand)
    hand << params[:deck][0][0]
    params[:deck][0] = params[:deck][0].drop(1)
  end

  def get_game
    @game = Game.find_by(group_id: params[:group_id])
  end

  def get_kou_otu
    @kou = Kou.find_by(game_id: params[:id])
    @otu = Otu.find_by(game_id: params[:id])
  end

  def get_gon
    gon.game_id = @game.id
    gon.group_id = @game.group_id
    gon.user_id = current_user.id
    gon.action_id = check_id(@game.action)
    gon.game = @game

    gon.kou = @kou
    gon.otu = @otu
  end

  def change_kou_otu(turn)
    if turn == "otu"
      turn = "kou"
    elsif turn == "kou"
      turn = "otu"
    end
  end

  def change_message(message)
    @game.message = message
  end

  def check_id(action)
    if action == "kou"
      return @kou.user_id
    elsif action == "otu"
      return @otu.user_id
    end
  end

  def check_turn_player(action)
    if action == "kou"
      return @kou
    elsif action == "otu"
      return @otu
    end
  end

  def draw_hand(action)
    check_turn_player(action).hand << @game.deck[0][0]
    check_turn_player(action).hand = check_turn_player(action).hand.shuffle
    @game.deck[0] = @game.deck[0].drop(1)
  end

  def check_card_number(number)
    case number
    when 1 then
      card_one
    when 2 then
      card_two
    when 21 then
      card_two_one
    when 3 then
      card_three
    when 4 then
      card_four
    when 5 then
      card_five
    when 6 then
      card_six
    when 7 then
      card_seven
    when 71 then
      card_seven_one
    when 8 then
      card_eight
    when 9 then
      card_nine
    when 91 then
      card_nine_one
    else
    end
  end

  def card_one
    if @game.one_used != "used" || check_turn_player(change_kou_otu(@game.turn)).condition == "guard"
      put_card_action
      render json:{number: @game.field_card.to_i}
      if check_turn_player(change_kou_otu(@game.turn)).condition == "guard"
        change_message("守護により発動しませんでした。")
      else
        change_message("最初の1なので、効果はありませんでした。")
      end
      @game.one_used = "used"
      turn_change_action
    else
      put_card_action
      draw_hand(change_kou_otu(@game.turn))
      update_all
      render json:{number: 9,card: check_turn_player(change_kou_otu(@game.turn)).hand}
      ##9と処理が同じなので９と同じ非同期通信へ
    end
  end

  def card_two
    if check_turn_player(change_kou_otu(@game.turn)).condition == "guard"
      put_card_action
      change_message("守護により発動しませんでした。")
      update_all
      turn_change_action
      render json:{number: 0}
    else
      put_card_action
      update_all
      render json:{number: params[:number].to_i}
    end
  end
  def card_two_one
    if check_turn_player(change_kou_otu(@game.turn)).hand[0] == params[:hand].to_i
      if params[:hand].to_i != 10
        @game.condition = @game.turn
        change_message(params[:hand] + "を指摘し、成功しました。")
        update_all
      else
        check_turn_player(change_kou_otu(@game.turn)).hand.delete_at(0)
        check_turn_player(change_kou_otu(@game.turn)).hand[0] = @game.deck[1][0]
        check_turn_player(change_kou_otu(@game.turn)).discard << "10"
        change_message(params[:hand] + "を指摘し、成功しましたが10であるため転生しました。")
        update_all
        turn_change_action
      end
    else
      change_message(params[:hand] + "を指摘しましたが、失敗に終わりました。")
      turn_change_action
    end
    render json:{number: params[:number].to_i}
  end

  def card_three
    if check_turn_player(change_kou_otu(@game.turn)).condition != "guard"
      put_card_action
      change_message("透視が発動しました。")
      update_all
      render json:{number: 3,card: check_turn_player(change_kou_otu(@game.turn)).hand[0]}
    else
      put_card_action
      change_message("守護があるため、能力は発動しませんでした。")
      render json:{number: 0}
      turn_change_action
    end
  end
  def card_four
    check_turn_player(@game.turn).condition = "guard"
    put_card_action
    change_message("守護が発動しました。")
    render json:{number: @game.field_card.to_i}
    turn_change_action
  end
  def card_five
    if check_turn_player(change_kou_otu(@game.turn)).condition != "guard"
      put_card_action
      draw_hand(change_kou_otu(@game.turn))
      update_all
      render json:{number: @game.field_card.to_i,card: check_turn_player(change_kou_otu(@game.turn)).hand}
    else
      put_card_action
      change_message("守護があるため、能力は発動しませんでした。")
      render json:{number: 0}
      turn_change_action
    end
  end

  def card_six
    if check_turn_player(change_kou_otu(@game.turn)).condition != "guard"
      put_card_action
      change_message("決闘が発動しました。")
      if @kou.hand[0] < @otu.hand[0]
        @game.action = "fight"
        @game.condition = "otu"
        @game.turn_count += 1
      elsif @kou.hand[0] > @otu.hand[0]
        @game.action = "fight"
        @game.condition = "kou"
        @game.turn_count += 1
      else
        change_message("引き分け（続行）となりました。")
        turn_change_action
      end
      render json:{number: @game.field_card.to_i}
      update_all
    else
      change_message("守護があるため、決闘は発動しませんでした。")
      put_card_action
      render json:{number: 0}
      turn_change_action
    end
  end

  def card_seven
    check_turn_player(@game.turn).condition = "wise"
    put_card_action
    change_message("未来視が発動しました。")
    render json:{number: @game.field_card.to_i}
    turn_change_action
  end
  def card_seven_one
    hand = check_turn_player(@game.turn).hand[1][params[:hand].to_i]
    check_turn_player(@game.turn).hand[1].delete_at(params[:hand].to_i)
    @game.deck[0] << check_turn_player(@game.turn).hand[1][0]
    @game.deck[0] << check_turn_player(@game.turn).hand[1][1]
    @game.deck[0] = @game.deck[0].shuffle
    check_turn_player(@game.turn).hand.delete_at(1)
    check_turn_player(@game.turn).hand << hand
    check_turn_player(@game.turn).condition = ""
    change_message("未来視によってカードが選ばれました。")
    update_all

    render json:{number: 0}
  end

  def card_eight
    if check_turn_player(change_kou_otu(@game.turn)).condition != "guard"
      change_message("交換が発動しました。")
      put_card_action
      card = @kou.hand[0]
      @kou.hand[0] = @otu.hand[0]
      @otu.hand[0] = card
      render json:{number: @game.field_card.to_i}
      turn_change_action
    else
      change_message("守護があるため、交換が発動しませんでした。")
      put_card_action
      render json:{number: 0}

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_message.html.haml
-if @game.turn == @game.action
  -if @action_player == "true"
    あなたのターンです。出すカードを選択して下さい。
  - else
    相手の選択を待っています。
-else
  - case @game.field_card
  - when 1 then
    = @game.field_card.to_s + "です。" + @action_player
  - when 2 then
    = @game.field_card.to_s + "です。"
  - when 3 then
    = @game.field_card.to_s + "です。"
  - when 4 then
    = @game.field_card.to_s + "です。"
  - when 5 then
    = @game.field_card.to_s + "です。"
  - when 6 then
    = @game.field_card.to_s + "です。確認したらボタンを押して下さい。"
  - when 7 then
    = @game.field_card.to_s + "です。"
  - when 8 then
    = @game.field_card.to_s + "です。"
  - when 9 then
    = @game.field_card.to_s + "です。"

app/views/games/index.html.haml
- if @game != nil
  - if @game.action == "kou" && current_user.id == Kou.find_by(game_id: @game.id).user_id
    -@action_player = "true"
  - elsif @game.action == "otu" && current_user.id == Otu.find_by(game_id: @game.id).user_id
    -@action_player = "true"
  - else
    -@action_player = "false"

.game-header
  .game-header__left
    = form_with url: group_games_path(params[:group_id]), local: true do |f|
      - if @game == nil
        .create-game__btn
          = f.submit "ゲーム開始", class: "start-game"
      - else
        .start-game
          ゲーム中
        = link_to '部屋削除',  group_path(params[:group_id],@game.id), method: :delete, class:'delete-group'


  .game-header__right
    .kou__discard
      - if @game != nil
        = "先攻捨て札："
        = @kou.discard
    .otu__discard
      - if @game != nil
        = "後攻捨て札："
        = @otu.discard
.game
  .game-side
  .game-main
    .game-main__enemy
      - if @game != nil
        - if @game.action == "fight"
          - Otu.find_by(game_id: @game.id).hand.each do |hand|
            .game-main__enemy--hand-card#card
              = hand
        - else
          - if current_user.id == Kou.find_by(game_id: @game.id).user_id
            - Otu.find_by(game_id: @game.id).hand.each do
              .game-main__enemy--hand-card#card
                0
          - if current_user.id == Otu.find_by(game_id: @game.id).user_id
            - Kou.find_by(game_id: @game.id).hand.each do
              .game-main__enemy--hand-card#card
                0

      - else
        .game-main__enemy--hand-card#card
          0
        .game-main__enemy--hand-card#card
          0
    .game-main__center
      - if @game != nil
        - if @game.condition == "started"
          .game-main__center--deck
            = "残  " + @game.deck[0].length.to_s + "枚"
          .game-main__center--field-card
            = @game.field_card
          .game-main__center--turn
            - if @game.turn == "kou"
              .your
                = "先攻"
            - else
              .enemy
                = "後攻"
        - elsif @game.condition == "kou" 
          .winner-message
            = User.find_by(id: @kou.user_id).nickname + " さんの勝利　"
            = link_to 'ゲーム削除',  group_game_path(params[:group_id],@game.id), method: :delete, class:'delete-game'
        - elsif @game.condition == "otu"
          .winner-message
            = User.find_by(id: @otu.user_id).nickname + " さんの勝利　"
            = link_to 'ゲーム削除',  group_game_path(params[:group_id],@game.id), method: :delete, class:'delete-game'
        - elsif @game.condition == "draw"
          .winner-message
            引き分け
            = link_to 'ゲーム削除',  group_game_path(params[:group_id],@game.id), method: :delete, class:'delete-game'
    .game-main__player
      .game-main__player--message
        .message
          - if @game != nil
            -# = render "message"
            = @game.message
      .game-main__player--hands
        - if @game != nil
          - if current_user.id == Kou.find_by(game_id: @game.id).user_id
            - if @kou.hand[1].class == Array
              - Kou.find_by(game_id: @game.id).hand[1].each_with_index do |hand,n|
                .game-main__player--hand-card#card{data:{hand: n+10}}
                  = hand
            - else
              - Kou.find_by(game_id: @game.id).hand.each_with_index do |hand,n|
                .game-main__player--hand-card#card{data:{hand: n}}
                  = hand
          - if current_user.id == Otu.find_by(game_id: @game.id).user_id
            - if @otu.hand[1].class == Array
              - Otu.find_by(game_id: @game.id).hand[1].each_with_index do |hand,n|
                .game-main__player--hand-card#card{data:{hand: n+10}}
                  = hand
            - else
              - Otu.find_by(game_id: @game.id).hand.each_with_index do |hand,n|
                .game-main__player--hand-card#card{data:{hand: n}}
                  = hand
        - else
          .game-main__player--hand-card#card
            1
          .game-main__player--hand-card#card
            10